_target_: algos.get_algo
# A2C Algorithm Configuration
name: "a2c"
policy: "MlpPolicy"
learning_rate: 0.0007
n_steps: 25
gamma: 0.99
ent_coef: 0.125
vf_coef: 0.5
max_grad_norm: 1.0
use_rms_prop: true
rms_prop_eps: 1.0e-05
normalize_advantage: false
verbose: 1