env:
  reward_persona: 'speedrunner'

model:
  name: 'A2C'
  policy: 'MlpPolicy'
  learning_rate: 0.0007
  n_steps: 5
  gamma: 0.99
  gae_lambda: 1.0
  ent_coef: 0.0
  vf_coef: 0.5
  max_grad_norm: 0.5
  use_rms_prop: True
  verbose: 1
  seed: 42
  total_timesteps: 100000
