env:
  reward_persona: 'speedrunner'

model:
  name: 'PPO'
  policy: 'MlpPolicy'
  learning_rate: 0.0003
  n_steps: 2048
  batch_size: 64
  n_epochs: 10
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.2
  ent_coef: 0.0
  verbose: 1
  seed: 42
  total_timesteps: 100000
